### PR TITLE
Improve documentation from building pam_hbac on BSD from source

### PR DESCRIPTION
**Pull request by jhrozek**
Includes steps to build pam_hbac from source including all dependencies.

### CODE REVIEW

**Comment by lslebodn** [comment]
> Then pam_hbac will read its configuration from /etc/pam_hbac.conf. Finally,
> specify the correct manual pages directory for FreeBSD:
>    --mandir=/usr/local/man
> It's not common to store configuration directly in /etc on FreeBSD.

Is there any reason why it cannot be in /usr/local/etc/?

**Comment by jhrozek** [comment]
On Fri, Apr 29, 2016 at 06:45:04AM -0700, lslebodn wrote:

> > Then pam_hbac will read its configuration from /etc/pam_hbac.conf. Finally,
> > specify the correct manual pages directory for FreeBSD:
> >    --mandir=/usr/local/man
> > It's not common to store configuration directly in /etc on FreeBSD.
> 
> Is there any reason why it cannot be in /usr/local/etc/?

No reason except me being used to configuration files under /etc/.

Is it more common on BSD to have them under /usr/local/etc ?

**Comment by lslebodn** [comment]
> Is it more common on BSD to have them under /usr/local/etc ?

Yes it is.
@see official documentation for LDAP
https://www.freebsd.org/doc/en/articles/ldap-auth/
There is mentioned /usr/local/etc/openldap/slapd.conf for server and /usr/local/etc/ldap.conf for client

**Comment by jhrozek** [comment]
On Fri, Apr 29, 2016 at 07:01:35AM -0700, lslebodn wrote:

> > Is it more common on BSD to have them under /usr/local/etc ?
> 
> Yes it is.
> @see official documentation for LDAP
> https://www.freebsd.org/doc/en/articles/ldap-auth/
> There is mentioned /usr/local/etc/openldap/slapd.conf for server and /usr/local/etc/ldap.conf for client

Thanks, I dropped the sysconfdir invocation which just uses the default
which is /usr/local/etc/pam_hbac.conf

**Comment by jhrozek** [comment]
@lslebodn OK to merge now?

**Comment by lslebodn** [comment]
On (02/05/16 00:42), Jakub Hrozek wrote:

> @lslebodn OK to merge now?
> 
> LGTM

But I think oyu yould also modify the Configuration section.
There is written:
  When the config file is created, put the following into /etc/pam.d/system
  or just the particular PAM service you would like secure:
       account    required    pam_hbac.so    ignore_unknown_user

I think you shoudl use full path to the pam module.
The same as it is recommended in official FreeBSD documentation
https://www.freebsd.org/doc/en/articles/ldap-auth/client.html#client-auth-pam

LS

**Comment by jhrozek** [comment]
On Tue, May 03, 2016 at 12:30:20AM -0700, lslebodn wrote:

> On (02/05/16 00:42), Jakub Hrozek wrote:
> 
> > @lslebodn OK to merge now?
> > 
> > LGTM
> 
> But I think oyu yould also modify the Configuration section.
> There is written:
>   When the config file is created, put the following into /etc/pam.d/system
>   or just the particular PAM service you would like secure:
>        account    required    pam_hbac.so    ignore_unknown_user
> 
> I think you shoudl use full path to the pam module.
> The same as it is recommended in official FreeBSD documentation
> https://www.freebsd.org/doc/en/articles/ldap-auth/client.html#client-auth-pam

Thanks, fixed. Also I fixed one trivial typo.

**Comment by lslebodn** [comment]
On (03/05/16 02:22), Jakub Hrozek wrote:

> On Tue, May 03, 2016 at 12:30:20AM -0700, lslebodn wrote:
> 
> > On (02/05/16 00:42), Jakub Hrozek wrote:
> > 
> > > @lslebodn OK to merge now?
> > > 
> > > LGTM
> > 
> > But I think oyu yould also modify the Configuration section.
> > There is written:
> >   When the config file is created, put the following into /etc/pam.d/system
> >   or just the particular PAM service you would like secure:
> >        account    required    pam_hbac.so    ignore_unknown_user
> > 
> > I think you shoudl use full path to the pam module.
> > The same as it is recommended in official FreeBSD documentation
> > https://www.freebsd.org/doc/en/articles/ldap-auth/client.html#client-auth-pam
> 
> Thanks, fixed. Also I fixed one trivial typo.
> 
> ACK

LS

**Pull request merged**
