### PR TITLE
Support Oracle Solaris.

### PR DESCRIPTION
**Pull request by jhrozek**
With the exception of the last patch, I think these patches can be reveiwed and merged while I work on the build instruction.

Tested on Solaris 11.

### CODE REVIEW

**Comment by preichl** [comment]
We should amend readme for solaris - we need to add docbook package.
Build was failling for me because a2x tried to validate man pages, but downloading dtd fail was failing and subsequently so did whole build. Installing docbook package seems to fix it for me.

**Comment by jhrozek** [comment]
OK, docbook added. I'm also thinking that we should explicitly add what Solaris kind are these instructions for. Solaris prior to 11 didn't have the pkg command at all and chances are OpenSolaris versions have had different package names.

**Comment by preichl** [comment]
I was able to successfully compile, install and test pam_hbac on solaris with this patch set.
Great work, thanks!

**Comment by jhrozek** [comment]
Thank you, in the patchset I just sent, I just squashed the last commit into "  build: Detect non-standard libldap location" and improved the documentation a bit.

**Comment by jhrozek** [comment]
@preichl OK to merge now? This would enable support for Solaris 11, I think we should support OpenSolaris (like Omnios) in a later patchset..

**Comment by preichl** [comment]
@jhrozek Yes, please.

**Pull request merged**
