### PR TITLE
Fix issue #55: Run integration tests during CI

### PR DESCRIPTION
**Pull request by jhrozek**
The attached commits use freeipa's demo server for running CI. This brings up the time to run the tests to almost 10 minutes, but I think having integration tests ran during build is worth it.

Fixes issue #55

### CODE REVIEW

**Comment by jhrozek** [comment]
If @preichl has no issues with a longer CI run, I will merge..

**Comment by preichl** [comment]
I don't know why yet, but integration tests fail for me but CI returns passed.

**Comment by jhrozek** [comment]
Hmm, I'm seeing all tests passed in Semaphore..so the issue is "only" us not failing CI when tests fail, right?

**Comment by jhrozek** [comment]
Actually, one test just failed for me, OK..

**Comment by jhrozek** [comment]
Yah, that was stupid, I should have changed the CI script to fail when some of the make targets fail. See the new version.

I also added yet another branch called cibreak: https://github.com/jhrozek/pam_hbac/tree/cibreak

It looks like CI now correctly reports the failure: https://semaphoreci.com/jhrozek/pam_hbac/branches/cibreak/builds/2

**Comment by preichl** [comment]
It works for me now. Thanks!

ACK

**Comment by jhrozek** [comment]
Thanks for the review

**Pull request merged**
